Trabalho-Api/Trabalho API/Models/Cliente.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Trabalho_API.Models
{
    public class Cliente
    {
        [Key]
        public int ClienteId { get; set; }

        [Required]
        public string Nome { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string Telefone { get; set; }

        [Required]
        public string CPF { get; set; }

        public string Cep { get; set; }
        public string Logradouro { get; set; }
        public string Bairro { get; set; }
        public string Localidade { get; set; }
        public string Uf { get; set; }

        [NotMapped]  // Não mapear para o banco de dados
        public IFormFile Foto { get; set; }
    }
}

Trabalho-Api/Trabalho API/Models/Endereco.cs
namespace Trabalho_API.Models
{
    public class Endereco
    {
        public string Cep { get; set; }
        public string Logradouro { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Localidade { get; set; }
        public string Uf { get; set; }
        public string Ibge { get; set; }
        public string Gia { get; set; }
        public string Ddd { get; set; }
        public string Siafi { get; set; }
    }
}

Trabalho-Api/Trabalho API/Models/ErrorViewModel.cs
namespace Trabalho_API.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Trabalho-Api/Trabalho API/Controllers/CepController.cs
using Microsoft.AspNetCore.Mvc;
using Trabalho_API.Models;
using Trabalho_API.Service;

namespace Trabalho_API.Controllers
{
    public class CepController : Controller
    {
        private readonly CorreiosService _correiosService;

        public CepController(CorreiosService correiosService)
        {
            _correiosService = correiosService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> BuscarEnderecoPorCep(string cep)
        {
            Endereco? endereco = await _correiosService.BuscarEnderecoPorCep(cep);
            if (endereco == null)
            {
                TempData["Mensagem"] = "CEP <strong> não </strong> encontrado";
            }
            return View("Index", endereco);
        }
    }
}

Trabalho-Api/Trabalho API/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Trabalho_API.Data;
using Trabalho_API.Models;

namespace Trabalho_API.Controllers
{
    public class ClienteController : Controller
    {
        private readonly AppCont _context;

        public ClienteController(AppCont context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            var clientes = await _context.Clientes.ToListAsync();
            return View(clientes);
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.ClienteId == id);

            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Cliente cliente)
        {
            if (id != cliente.ClienteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.ClienteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.ClienteId == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            _context.Clientes.Remove(cliente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.Clientes.Any(e => e.ClienteId == id);
        }
    }
}

Trabalho-Api/Trabalho API/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Trabalho_API.Models;

namespace Trabalho_API.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Trabalho-Api/Trabalho API/Views/Cep/Index.cshtml
@model Trabalho_API.Models.Endereco

<h2>Busca CEP</h2>

<form id="form-cep" method="post" action="@Url.Action("BuscarEnderecoPorCep", "Cep")">
    <div class="form-group row, col-md-12">
        <label asp-for="Cep" class="control-label, col-md-10"></label>

        <input asp-for="Cep" class="form-control, col-md-2" maxlength="8" required />
        <input type="submit" value="Buscar" id="btnBuscar" class="btn btn-primary btn-sm" style="margin-top:-3px;" />

        <span id="loader" style="display:none;">
            <img src="~/img/loading.gif" alt="Carregando..." class="img-fluid" style="width:30px;" />
        </span>
    </div>
</form>"

<div class="col-sm-7">
    <hr />
</div>

@if (Model != null)
{
    <div id="endereco">
        <h5>Endereço encontrado</h5>
        <p>
            <strong>CEP:</strong> <input asp-for="Cep" class="form-control" readonly /> <br />
            <strong>Logradouro:</strong> <input asp-for="Logradouro" class="form-control" readonly /> <br />
            <strong>Complemento:</strong> <input asp-for="Complemento" class="form-control" readonly /> <br />
            <strong>Bairro:</strong> <input asp-for="Bairro" class="form-control" readonly /> <br />
            <strong>Cidade:</strong> <input asp-for="Localidade" class="form-control" readonly /> <br />
            <strong>Estado:</strong> <input asp-for="Uf" class="form-control" readonly /> <br />
        </p>
    </div>
}
else
{
    <div id="mensagem">
        <h3>@Html.Raw(TempData["Mensagem"])</h3>
    </div>
}

<script scr="Https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $("#form-cep").submit(function () {
            $("#loader").show();
            $("#btnBuscar").replaceWith(loader);
        });
    });
</script>

Trabalho-Api/Trabalho API/Views/Cliente/Create.cshtml
@model Trabalho_API.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="Cep">CEP</label>
                <div class="input-group">
                    <input asp-for="Cep" id="Cep" maxlength="8" class="form-control" required>
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" onclick="buscarCep()">Buscar CEP</button>
                    </div>
                    <div class="invalid-feedback">CEP é obrigatório.</div>
                </div>
            </div>

            <div class="form-group">
                <label for="Logradouro">Logradouro</label>
                <input asp-for="Logradouro" id="Logradouro" class="form-control">
            </div>

            <div class="form-group">
                <label for="Bairro">Bairro</label>
                <input asp-for="Bairro" id="Bairro" class="form-control">
            </div>

            <div class="form-group">
                <label for="Localidade">Cidade</label>
                <input asp-for="Localidade" id="Localidade" class="form-control">
            </div>

            <div class="form-group">
                <label for="Uf">Estado</label>
                <input asp-for="Uf" id="Uf" class="form-control">
            </div>

            <div class="form-group">
                <label for="Foto">Foto</label>
                <input type="file" asp-for="Foto" class="form-control-file">
                <small class="form-text text-muted">Carregue a foto da pessoa.</small>
            </div>

            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<script>
    function buscarCep() {
        var cep = $('#Cep').val();
        if (cep.length == 8) {
            $.ajax({
                url: `https://viacep.com.br/ws/${cep}/json/`,
                type: "GET",
                success: function (data) {
                    if (data) {
                        $('#Logradouro').val(data.logradouro);
                        $('#Bairro').val(data.bairro);
                        $('#Localidade').val(data.localidade);
                        $('#Uf').val(data.uf);
                    }
                },
                error: function (error) {
                    alert('Erro ao buscar CEP');
                }
            });
        }
    }
</script>

Trabalho-Api/Trabalho API/Views/Cliente/Delete.cshtml
@model Trabalho_API.Models.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cep)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cep)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logradouro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logradouro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bairro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Localidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Localidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Uf)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Uf)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ClienteId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Trabalho-Api/Trabalho API/Views/Cliente/Details.cshtml
@model Trabalho_API.Models.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cep)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cep)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logradouro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logradouro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bairro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Localidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Localidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Uf)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Uf)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ClienteId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Trabalho-Api/Trabalho API/Views/Cliente/Edit.cshtml
@model Trabalho_API.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ClienteId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cep" class="control-label"></label>
                <input asp-for="Cep" class="form-control" />
                <span asp-validation-for="Cep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logradouro" class="control-label"></label>
                <input asp-for="Logradouro" class="form-control" />
                <span asp-validation-for="Logradouro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bairro" class="control-label"></label>
                <input asp-for="Bairro" class="form-control" />
                <span asp-validation-for="Bairro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Localidade" class="control-label"></label>
                <input asp-for="Localidade" class="form-control" />
                <span asp-validation-for="Localidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Uf" class="control-label"></label>
                <input asp-for="Uf" class="form-control" />
                <span asp-validation-for="Uf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Trabalho-Api/Trabalho API/Views/Cliente/Index.cshtml
@model IEnumerable<Trabalho_API.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CPF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cep)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Logradouro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bairro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Localidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Uf)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CPF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cep)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Logradouro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bairro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Localidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Uf)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ClienteId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ClienteId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ClienteId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>